In [2]:
import numpy as np  

v = 7.6
g = 9.80

theta = np.arange(12,20,2)[None,:]/180.0*(np.pi)

h = 0.0
tmax = h + ((2 * v) * np.sin(theta)) / g
vecT = tmax*np.linspace(0,1,100)[:,None]

for h in np.arange(0.0,5.0,0.76):
    tmax = h + ((2 * v) * np.sin(theta)) / g
    print(tmax)

[[0.32247528 0.3752258  0.42751916 0.47929166]]
[[1.08247528 1.1352258  1.18751916 1.23929166]]
[[1.84247528 1.8952258  1.94751916 1.99929166]]
[[2.60247528 2.6552258  2.70751916 2.75929166]]
[[3.36247528 3.4152258  3.46751916 3.51929166]]
[[4.12247528 4.1752258  4.22751916 4.27929166]]
[[4.88247528 4.9352258  4.98751916 5.03929166]]
